name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      with: 
        major_pattern: "major:"
        minor_pattern: "feat:"
        version_format: "${major}.${feat}.${patch}-prerelease${increment}"
      id: version
        
    - name: Docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "NEW VERSION: $NEW_VERSION!!!!!!!"
        
    # - name: Build Docker Image
    #   run : |
    #     docker build -t joseav99/docker-graphql:0.0.2 .
    #     docker build -t joseav99/docker-graphql .
        
        
    # - name: Push docker image
    #   run : |
    #     docker push  joseav99/docker-graphql:0.0.2
    #     docker push  joseav99/docker-graphql
        
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
